apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fractalwoodstories-product-service-images-pvc
  namespace: fractalwoodstories
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: fractalwoodstories-product-service-images
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi