apiVersion: v1
kind: PersistentVolume
metadata:
  name: fractalwoodstories-product-service-images
  namespace: fractalwoodstories
spec:
  storageClassName: nfs-client
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/usb/fractalwoodstories/images"

